/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LocationLocationIdImport } from './routes/location.$locationId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LocationLocationIdRoute = LocationLocationIdImport.update({
  id: '/location/$locationId',
  path: '/location/$locationId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/location/$locationId': {
      id: '/location/$locationId'
      path: '/location/$locationId'
      fullPath: '/location/$locationId'
      preLoaderRoute: typeof LocationLocationIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/location/$locationId': typeof LocationLocationIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/location/$locationId': typeof LocationLocationIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/location/$locationId': typeof LocationLocationIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/location/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/location/$locationId'
  id: '__root__' | '/' | '/location/$locationId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LocationLocationIdRoute: typeof LocationLocationIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LocationLocationIdRoute: LocationLocationIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/location/$locationId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/location/$locationId": {
      "filePath": "location.$locationId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
